%% Compile the wrapper for readOBJ
mex readOBJ_mex.cpp ...
    -I../../Depends/libigl/include ...
    -I/usr/include/eigen3 ... %% Change this path to point to your copy of Eigen
    -output readOBJFast